<?php

/**
 * MASAR - Certificates Large Realistic Dataset Seeder
 *
 * Builds the idempotent certificate dataset for the REAL student used by the
 * MASAR Student Login requests (mammuslim2003@gmail.com, student 1498), using
 * the REAL driving company TestHire Solutions (100161) and the REAL admin.
 *
 * Dataset (trainings 100400-100422, all owned by TestHire, specialization mix):
 *
 *   Eligible (8)     100400-100407   accepted app + completed session + the
 *                                    training has ENDED (ends_at <= NOW()) and
 *                                    no certificate row exists -> requestable.
 *                                    Free: 100400-100403, paid: 100404-100407.
 *   Pending  (5)     100408-100412   driven through certificate_service_request.
 *   Issued   (6)     100413-100418   request + confirm (issued_at/number added).
 *   Revoked  (3)     100419-100421   request + confirm + revoke (kept number +
 *                                    issued_at + revocation_reason).
 *   Unfinished (1)   100422          accepted app + completed session but the
 *                                    training is STILL RUNNING
 *                                    (ends_at > NOW()) -> NOT eligible, NOT
 *                                    requestable. Proves the time gate that
 *                                    certificate eligibility now enforces.
 *
 * Every state transition goes through the REAL certificate service (request /
 * confirm / revoke) - no database bypass of business rules. Duplicate rows are
 * never created; each (student, training) pair is checked first and skipped
 * when it already converged. certificate_number is always generated by the
 * existing logic. is_paid always mirrors training_listings.is_paid.
 *
 * Deterministic lookup key per pair: (student_id, training_id).
 *
 * Usage:
 *     php tests/certificates_test_data_seeder.php          # converge dataset
 *     php tests/certificates_test_data_seeder.php --reset  # rebuild canonical
 *                                                          # states from scratch
 *
 * Run from the backend root.
 */

declare(strict_types=1);

error_reporting(E_ALL);
ini_set('display_errors', '1');

define('BASE', dirname(__DIR__) . '/');

require_once BASE . 'vendor/autoload.php';
if (file_exists(BASE . '.env')) {
    Dotenv\Dotenv::createUnsafeImmutable(BASE)->safeLoad();
}

require_once BASE . 'app/core/database/connection.php';
require_once BASE . 'app/core/database/query.php';
require_once BASE . 'app/modules/certificates/services/certificate_service.php';
require_once __DIR__ . '/certificates_fixtures.php';

$failures = 0;

function seed_check(string $label, bool $cond): void
{
    global $failures;
    echo ($cond ? 'PASS' : 'FAIL') . " - {$label}\n";
    if (!$cond) {
        $failures++;
    }
}

$reset = in_array('--reset', $argv ?? [], true);

/*
 |--------------------------------------------------------------------------
 | Identity resolution (REAL records only)
 |--------------------------------------------------------------------------
 */

$student       = cf_resolve_student_first(['mammuslim2003@gmail.com']);
$company       = cf_resolve_company('company@test.local');
$admin_user_id = cf_resolve_user_id_first(['admin@test.local', 'admin@masar.eg', 'compliance@masar.eg']);

$STUDENT_ID = (int) $student['student_id'];
$STUDENT_UID = (int) $student['user_id'];
$COMPANY_ID = (int) $company['company_id'];
$COMPANY_UID = (int) $company['user_id'];

echo "== Identity ==\n";
seed_check('student resolved (mammuslim2003@gmail.com / student 1498)', $STUDENT_ID === 1498 && $STUDENT_UID === 100588);
seed_check('TestHire Solutions (100161) resolved', $COMPANY_ID === 100161 && $COMPANY_UID === 100595);
seed_check('real admin resolved (admin@masar.eg)', $admin_user_id > 0);

if ($STUDENT_ID !== 1498 || $COMPANY_ID !== 100161 || $admin_user_id <= 0) {
    echo "\nAborted: required real accounts were not resolved.\n";
    exit(1);
}

/*
 |--------------------------------------------------------------------------
 | Dataset definition
 |--------------------------------------------------------------------------
 | end_days_ago > 0  -> ENDED training (finished, eligible to complete).
 | end_days_ago < 0  -> STILL RUNNING (end in |end_days_ago| days from now).
 */

$NOW = time();

$TRAININGS = [
    // --- Eligible free ---
    ['id' => 100400, 'title' => 'Backend Services Integration Sprint',       'spec' => 199, 'paid' => false, 'type' => 'project_based', 'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 1, 'comp' => null,     'cap' => 16, 'trial' => 7,  'weeks' => 13, 'end' => -12],
    ['id' => 100401, 'title' => 'REST API Security Hardening',                'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'remote',  'loc' => 'Remote',              'lead' => 0, 'comp' => null,     'cap' => 12, 'trial' => 7,  'weeks' => 8,  'end' => -34],
    ['id' => 100402, 'title' => 'Event-Driven Architecture Workshop',         'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Giza, Egypt',         'lead' => 1, 'comp' => null,     'cap' => 20, 'trial' => 7,  'weeks' => 6,  'end' => -21],
    ['id' => 100403, 'title' => 'MySQL Query Optimization Lab',               'spec' => 199, 'paid' => false, 'type' => 'project_based', 'mode' => 'onsite',  'loc' => 'Cairo, Egypt',        'lead' => 0, 'comp' => null,     'cap' => 10, 'trial' => 7,  'weeks' => 5,  'end' => -9],
    // --- Eligible paid ---
    ['id' => 100404, 'title' => 'Dockerized Backend Deployment Bootcamp',     'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => 1500.00,  'cap' => 14, 'trial' => 14, 'weeks' => 10, 'end' => -45],
    ['id' => 100405, 'title' => 'High-Performance Laravel Systems',           'spec' => 199, 'paid' => true,  'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Alexandria, Egypt',   'lead' => 0, 'comp' => 1200.00,  'cap' => 12, 'trial' => 7,  'weeks' => 9,  'end' => -18],
    ['id' => 100406, 'title' => 'Kubernetes Orchestration Essentials',        'spec' => 199, 'paid' => true,  'type' => 'hands_on',      'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => 2000.00,  'cap' => 18, 'trial' => 14, 'weeks' => 8,  'end' => -27],
    ['id' => 100407, 'title' => 'Backend Data Pipelines Practicum',           'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 1, 'comp' => 1800.00,  'cap' => 10, 'trial' => 7,  'weeks' => 12, 'end' => -6],
    // --- Pending (request only) ---
    ['id' => 100408, 'title' => 'Real-Time Notification Systems',             'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'remote',  'loc' => 'Remote',              'lead' => 0, 'comp' => null,     'cap' => 15, 'trial' => 7,  'weeks' => 7,  'end' => -15],
    ['id' => 100409, 'title' => 'API Rate Limiting & Queues',                 'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 0, 'comp' => null,     'cap' => 12, 'trial' => 7,  'weeks' => 6,  'end' => -25],
    ['id' => 100410, 'title' => 'Secure Authentication Flows',                'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => 1400.00,  'cap' => 14, 'trial' => 14, 'weeks' => 8,  'end' => -40],
    ['id' => 100411, 'title' => 'Redis Caching Patterns',                     'spec' => 199, 'paid' => true,  'type' => 'hands_on',      'mode' => 'onsite',  'loc' => 'Giza, Egypt',         'lead' => 1, 'comp' => 1100.00,  'cap' => 10, 'trial' => 7,  'weeks' => 5,  'end' => -11],
    ['id' => 100412, 'title' => 'Serverless Backend Functions',               'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 0, 'comp' => 1700.00,  'cap' => 16, 'trial' => 14, 'weeks' => 7,  'end' => -32],
    // --- Issued (request + confirm) ---
    ['id' => 100413, 'title' => 'Database Sharding Fundamentals',             'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 0, 'comp' => null,     'cap' => 13, 'trial' => 7,  'weeks' => 8,  'end' => -52],
    ['id' => 100414, 'title' => 'Backend Refactoring Carousel',               'spec' => 199, 'paid' => false, 'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => null,     'cap' => 11, 'trial' => 7,  'weeks' => 9,  'end' => -29],
    ['id' => 100415, 'title' => 'Test-Driven Backend Design',                 'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Alexandria, Egypt',   'lead' => 0, 'comp' => null,     'cap' => 12, 'trial' => 7,  'weeks' => 6,  'end' => -16],
    ['id' => 100416, 'title' => 'Cloud-Native Monolith Migration',            'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => 2200.00,  'cap' => 14, 'trial' => 14, 'weeks' => 11, 'end' => -48],
    ['id' => 100417, 'title' => 'Distributed Systems Patterns',               'spec' => 199, 'paid' => true,  'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 1, 'comp' => 1900.00,  'cap' => 15, 'trial' => 14, 'weeks' => 10, 'end' => -38],
    ['id' => 100418, 'title' => 'Performance Budgeting for APIs',             'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 0, 'comp' => 1300.00,  'cap' => 10, 'trial' => 7,  'weeks' => 7,  'end' => -14],
    // --- Revoked (request + confirm + revoke) ---
    ['id' => 100419, 'title' => 'Incident Response Runbooks',                 'spec' => 199, 'paid' => false, 'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Cairo, Egypt',        'lead' => 0, 'comp' => null,     'cap' => 12, 'trial' => 7,  'weeks' => 5,  'end' => -58, 'reason' => 'Administrative verification failed'],
    ['id' => 100420, 'title' => 'WebSockets & Streaming APIs',                'spec' => 199, 'paid' => false, 'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => null,     'cap' => 14, 'trial' => 7,  'weeks' => 8,  'end' => -42, 'reason' => 'Duplicate certificate issued'],
    ['id' => 100421, 'title' => 'Multi-Tenancy Backend Course',               'spec' => 199, 'paid' => true,  'type' => 'hands_on',      'mode' => 'hybrid',  'loc' => 'Giza, Egypt',         'lead' => 1, 'comp' => 1600.00,  'cap' => 11, 'trial' => 14, 'weeks' => 9,  'end' => -62, 'reason' => 'Training records could not be verified'],
    // --- Unfinished (NOT eligible: ends_at > NOW()) ---
    ['id' => 100422, 'title' => 'Cache Invalidation Strategies Sprint',       'spec' => 199, 'paid' => true,  'type' => 'project_based', 'mode' => 'remote',  'loc' => 'Remote',              'lead' => 1, 'comp' => 1250.00,  'cap' => 12, 'trial' => 7,  'weeks' => 9,  'end' => 20],
];

$PENDING_IDS  = [100408, 100409, 100410, 100411, 100412];
$ISSUED_IDS   = [100413, 100414, 100415, 100416, 100417, 100418];
$REVOKED_IDS  = [100419, 100420, 100421];
$ELIGIBLE_IDS = [100400, 100401, 100402, 100403, 100404, 100405, 100406, 100407];
$UNFINISHED   = 100422;

/*
| Grade data. Only issued / revoked dataset certificates carry a grade:
|   issued  -> grade/grade_label describe the achieved result.
|   revoked -> preserves the historical grade the certificate carried when it
|              was issued (never cleared on revocation).
|   pending / eligible / unfinished -> no grade is ever set.
| The distribution varies across the certificates (A+ / A / B+ / B / C+ / C).
*/
$GRADES = [
    100413 => ['grade' => 'A+', 'grade_label' => 'Excellent'],
    100414 => ['grade' => 'A',  'grade_label' => 'Excellent'],
    100415 => ['grade' => 'B+', 'grade_label' => 'Very Good'],
    100416 => ['grade' => 'B',  'grade_label' => 'Very Good'],
    100417 => ['grade' => 'C+', 'grade_label' => 'Good'],
    100418 => ['grade' => 'C',  'grade_label' => 'Good'],
    100419 => ['grade' => 'A',  'grade_label' => 'Excellent'],
    100420 => ['grade' => 'B+', 'grade_label' => 'Very Good'],
    100421 => ['grade' => 'C+', 'grade_label' => 'Good'],
];

/*
 |--------------------------------------------------------------------------
 | Helpers (idempotent, own-row only)
 |--------------------------------------------------------------------------
 */

$student_profile = db_fetch_one(
    "SELECT s.full_name, s.phone, s.city, s.university_id, s.field_id,
            s.specialization_id, s.graduation_year, u.email
     FROM students s JOIN users u ON u.id = s.user_id
     WHERE s.id = ? LIMIT 1",
    [$STUDENT_ID]
);
$university_name = (string) ((db_fetch_one("SELECT name FROM universities WHERE id = ? LIMIT 1", [(int) ($student_profile['university_id'] ?? 0)])['name'] ?? ''));

function dataset_dates(array $t, int $now): array
{
    $days = (int) $t['end'];
    $end  = $now + $days * 86400;
    $start = $end - (int) $t['weeks'] * 7 * 86400;
    return [
        'published' => $start - 20 * 86400,
        'deadline'  => $start - 3 * 86400,
        'start'     => $start,
        'end'       => $end,
    ];
}

function ensure_training(array $t, int $company_id): bool
{
    $existing = db_fetch_one("SELECT id, company_id FROM training_listings WHERE id = ? LIMIT 1", [(int) $t['id']]);
    if ($existing) {
        if ((int) ($existing['company_id'] ?? 0) !== $company_id) {
            return false;
        }
        $dates = dataset_dates($t, time());
        $description = 'A "TestHire Certified" hands-on program for ' .
            ((int) $t['paid'] ? 'paid ' : 'free ') . 'backend development practice: ' . $t['title'] . '.';
        db_execute(
            "UPDATE training_listings SET
                specialization_id = ?, title = ?, description = ?, training_type = ?, mode = ?,
                may_lead_to_employment = ?, is_paid = ?, compensation_amount = ?, compensation_currency = 'EGP',
                trial_period_days = ?, capacity = ?, starts_at = ?, ends_at = ?, application_deadline = ?,
                location = ?, updated_at = NOW()
             WHERE id = ?",
            [
                (int) $t['spec'], $t['title'], $description,
                $t['type'], $t['mode'], (int) $t['lead'], (int) $t['paid'], $t['comp'],
                (int) $t['trial'], (int) $t['cap'],
                date('Y-m-d H:i:s', $dates['start']),
                date('Y-m-d H:i:s', $dates['end']),
                date('Y-m-d H:i:s', $dates['deadline']),
                $t['loc'],
                (int) $t['id'],
            ]
        );
        return true;
    }
    $dates = dataset_dates($t, time());
    $description = 'A "TestHire Certified" hands-on program for ' .
        ((int) $t['paid'] ? 'paid ' : 'free ') . 'backend development practice: ' . $t['title'] . '.';
    db_execute(
        "INSERT INTO training_listings
            (id, company_id, specialization_id, title, description, training_type, mode,
             may_lead_to_employment, is_paid, compensation_amount, compensation_currency,
             trial_period_days, capacity, status, published_at, starts_at, ends_at,
             application_deadline, location, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'EGP', ?, ?, 'published', ?, ?, ?, ?, ?, NOW(), NOW())",
        [
            (int) $t['id'], $company_id, (int) $t['spec'], $t['title'], $description,
            $t['type'], $t['mode'], (int) $t['lead'], (int) $t['paid'],
            $t['comp'],
            (int) $t['trial'], (int) $t['cap'],
            date('Y-m-d H:i:s', $dates['published']),
            date('Y-m-d H:i:s', $dates['start']),
            date('Y-m-d H:i:s', $dates['end']),
            date('Y-m-d H:i:s', $dates['deadline']),
            $t['loc'],
        ]
    );
    return true;
}

function ensure_application(array $t, array $profile, int $company_id, int $student_id, string $university_name): int
{
    $existing = db_fetch_one(
        "SELECT id, status FROM training_applications WHERE training_id = ? AND student_id = ?",
        [(int) $t['id'], $student_id]
    );
    if ($existing) {
        return (int) $existing['id'];
    }
    $dates = dataset_dates($t, time());
    db_execute(
        "INSERT INTO training_applications
            (training_id, student_id, company_id, message, full_name, email, phone, city,
             why_interested, what_to_learn, skills, status, applied_at, reviewed_at, reviewed_by,
             university, applicant_type, academic_year, graduation_year, motivation)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'accepted', ?, ?, ?, ?, 'student', ?, ?, ?)",
        [
            (int) $t['id'], $student_id, $company_id,
            'I want to sharpen my backend skills through a supervised ' . $t['title'] . ' program.',
            $profile['full_name'], $profile['email'], $profile['phone'], $profile['city'],
            'Hands-on practice in production-grade backend engineering with real mentorship.',
            'Design, build and ship a complete backend module using the course stack.',
            'PHP, Laravel, MySQL, REST APIs, Git, Docker',
            date('Y-m-d H:i:s', $dates['deadline']),
            date('Y-m-d H:i:s', $dates['deadline'] + 2 * 86400),
            $company_id,
            $university_name, $profile['academic_year'] ?? null, $profile['graduation_year'] ? (int) $profile['graduation_year'] : null,
            'Looking for structured experience with measurable outcomes before graduation.',
        ]
    );
    return (int) db_last_insert_id();
}

function ensure_completed_session(array $t, int $application_id, int $student_id, int $company_id): bool
{
    $dates = dataset_dates($t, time());
    $unfinished = ((int) $t['end']) > 0;
    $actual_end = $unfinished
        ? date('Y-m-d H:i:s', time() - 5 * 86400)
        : date('Y-m-d H:i:s', $dates['end']);

    $existing = db_fetch_one(
        "SELECT id, status FROM training_sessions WHERE application_id = ? LIMIT 1",
        [$application_id]
    );
    if ($existing) {
        return strtolower((string) $existing['status']) === 'completed';
    }
    db_execute(
        "INSERT INTO training_sessions
            (application_id, training_id, student_id, company_id, status, started_at,
             trial_started_at, trial_ends_at, student_continuation_confirmed_at,
             actual_ended_at, employment_opportunity, created_at, updated_at)
         VALUES (?, ?, ?, ?, 'completed', ?, ?, ?, ?, ?, ?, NOW(), NOW())",
        [
            $application_id, (int) $t['id'], $student_id, $company_id,
            date('Y-m-d H:i:s', $dates['start']),
            date('Y-m-d H:i:s', $dates['start']),
            date('Y-m-d H:i:s', $dates['start'] + (int) $t['trial'] * 86400),
            date('Y-m-d H:i:s', $dates['start'] + (int) $t['trial'] * 2 * 86400),
            $actual_end, (int) $t['lead'],
        ]
    );
    return true;
}

function dataset_cert(int $student_id, int $training_id): array
{
    $row = db_fetch_one(
        "SELECT c.id, c.certificate_code, c.status, c.training_id, c.revocation_reason
         FROM certificates c WHERE c.student_id = ? AND c.training_id = ?
         LIMIT 1",
        [$student_id, $training_id]
    );
    return $row ?: [];
}

/*
 |--------------------------------------------------------------------------
 | Build / converge the dataset
 |--------------------------------------------------------------------------
 */

$student_user = ['id' => $STUDENT_UID, 'role' => 'student'];
$company_user = ['id' => $COMPANY_UID, 'role' => 'company'];
$admin_user   = ['id' => $admin_user_id, 'role' => 'admin', 'is_admin' => true];

echo "\n== Ensuring trainings / applications / sessions (100400-100422) ==\n";

foreach ($TRAININGS as $t) {
    seed_check('training ' . $t['id'] . ' exists or was created under TestHire', ensure_training($t, $COMPANY_ID));
}

$collision = db_fetch_one(
    "SELECT COUNT(*) AS n FROM training_listings
     WHERE id BETWEEN 100400 AND 100422 AND company_id <> ?",
    [$COMPANY_ID]
);
seed_check('no id collision with a foreign training', (int) ($collision['n'] ?? 0) === 0);
if ((int) ($collision['n'] ?? 0) !== 0) {
    echo "\nAborted: dataset id range collides with trainings owned by another company.\n";
    exit(1);
}

foreach ($TRAININGS as $t) {
    $app_id = ensure_application($t, $student_profile, $COMPANY_ID, $STUDENT_ID, $university_name);
    seed_check('application for ' . $t['id'] . ' is accepted & persisted', $app_id > 0 && strtolower((string) ((db_fetch_one("SELECT status FROM training_applications WHERE id = ? LIMIT 1", [$app_id])['status'] ?? ''))) === 'accepted');
    seed_check('completed session for ' . $t['id'], ensure_completed_session($t, $app_id, $STUDENT_ID, $COMPANY_ID));
}

/*
 |--------------------------------------------------------------------------
 | Certificate states through the REAL service
 |--------------------------------------------------------------------------
 */

function converge_cert(bool $reset, array $student_user, array $company_user, int $student_id, int $training_id, string $target, string $reason = ''): string
{
    $cert = dataset_cert($student_id, $training_id);
    $status = $cert ? strtolower((string) $cert['status']) : '';
    $cid    = $cert ? (int) $cert['id'] : 0;

    if ($reset && $cert) {
        db_execute("DELETE FROM certificate_appeals WHERE certificate_id = ?", [$cid]);
        db_execute("DELETE FROM notifications WHERE entity_type = 'certificate' AND entity_id = ?", [$cid]);
        db_execute("DELETE FROM certificates WHERE id = ?", [$cid]);
        $cert = [];
        $status = '';
        $cid = 0;
    }

    if ($status === $target) {
        return $target . ' (already, id ' . $cid . ')';
    }

    if ($target === 'pending') {
        if ($status === '') {
            $req = certificate_service_request($student_user, ['training_id' => $training_id]);
            if (($req['success'] ?? false) !== true) {
                return 'request-failed';
            }
            return 'pending';
        }
        return 'conflict-with-' . $status;
    }

    if ($target === 'issued') {
        if ($status === '') {
            $req = certificate_service_request($student_user, ['training_id' => $training_id]);
            if (($req['success'] ?? false) !== true) {
                return 'request-failed';
            }
            $cert = dataset_cert($student_id, $training_id);
            $status = strtolower((string) ($cert['status'] ?? ''));
            $cid = (int) ($cert['id'] ?? 0);
        }
        if ($status === 'issued') {
            return 'issued (id ' . $cid . ')';
        }
        if ($status === 'pending') {
            $conf = certificate_service_confirm($company_user, (int) $cid);
            if (($conf['success'] ?? false) !== true) {
                return 'confirm-failed';
            }
            return 'issued';
        }
        return 'conflict-with-' . $status;
    }

    if ($target === 'revoked') {
        if ($status === '') {
            $req = certificate_service_request($student_user, ['training_id' => $training_id]);
            if (($req['success'] ?? false) !== true) {
                return 'request-failed';
            }
            $cert = dataset_cert($student_id, $training_id);
            $status = strtolower((string) ($cert['status'] ?? ''));
            $cid = (int) ($cert['id'] ?? 0);
        }
        if ($status === 'revoked') {
            return 'revoked (id ' . $cid . ')';
        }
        if (in_array($status, ['pending', 'issued'], true)) {
            $conf = certificate_service_confirm($company_user, (int) $cid);
            if (($conf['success'] ?? false) !== true) {
                return 'confirm-failed';
            }
            $rev = certificate_service_revoke($company_user, (int) $cid, ['reason' => $reason]);
            if (($rev['success'] ?? false) !== true) {
                return 'revoke-failed';
            }
            return 'revoked';
        }
        return 'conflict-with-' . $status;
    }

    return 'unknown-target';
}

echo "\n== Driving certificate states through the service ==\n";

$state_report = [];
$buckets = [];
foreach ($TRAININGS as $t) {
    $tid = (int) $t['id'];
    if (in_array($tid, $PENDING_IDS, true)) {
        $bucket = 'pending';
    } elseif (in_array($tid, $ISSUED_IDS, true)) {
        $bucket = 'issued';
    } elseif (in_array($tid, $REVOKED_IDS, true)) {
        $bucket = 'revoked';
    } elseif (in_array($tid, $ELIGIBLE_IDS, true)) {
        $bucket = 'eligible';
    } elseif ($tid === $UNFINISHED) {
        $bucket = 'unfinished';
    } else {
        $bucket = 'unknown';
    }
    $buckets[$tid] = $bucket;

    if ($bucket === 'eligible' || $bucket === 'unfinished') {
        $existing = dataset_cert($STUDENT_ID, $tid);
        if ($existing) {
            // Any certificate on an eligible/unfinished dataset training is a
            // test-owned leftover from a crashed run - converge by removing it.
            db_execute("DELETE FROM certificate_appeals WHERE certificate_id = ?", [(int) $existing['id']]);
            db_execute("DELETE FROM notifications WHERE entity_type = 'certificate' AND entity_id = ?", [(int) $existing['id']]);
            db_execute("DELETE FROM certificates WHERE id = ?", [(int) $existing['id']]);
            seed_check("$tid cleaned of a leftover certificate (crashed-run residue)", true);
        } else {
            seed_check("$tid stays eligible-free (no cert)", true);
        }
        continue;
    }

    $reason = (string) ($t['reason'] ?? '');
    $outcome = converge_cert($reset, $student_user, $company_user, $STUDENT_ID, $tid, $bucket, $reason);
    seed_check("certificate $tid -> {$outcome}", str_starts_with($outcome, $bucket));
    $state_report[$tid] = $outcome;
}

echo "\n== Assigning grade data (issued + revoked only, fill-if-null) ==\n";

$grade_tids = array_keys($GRADES);
$grade_certs = db_fetch_all(
    "SELECT c.id, c.training_id, c.grade, c.grade_label
     FROM certificates c
     WHERE c.student_id = ?
       AND c.training_id IN (" . implode(',', array_fill(0, count($grade_tids), '?')) . ")
     ORDER BY c.training_id",
    array_merge([$STUDENT_ID], $grade_tids)
);
$grades_assigned = 0;
foreach ($grade_certs as $cert) {
    $pair = $GRADES[(int) $cert['training_id']] ?? null;
    if ($pair === null) { continue; }
    $has_grade = $cert['grade'] !== null && (string) $cert['grade'] !== '';
    if (!$has_grade) {
        db_execute(
            "UPDATE certificates SET grade = ?, grade_label = ?, updated_at = NOW() WHERE id = ?",
            [$pair['grade'], $pair['grade_label'], (int) $cert['id']]
        );
        $grades_assigned++;
    }
}
$grade_certs_after = db_fetch_all(
    "SELECT c.training_id, c.grade, c.grade_label
     FROM certificates c
     WHERE c.student_id = ?
       AND c.training_id IN (" . implode(',', array_fill(0, count($grade_tids), '?')) . ")
     ORDER BY c.training_id",
    array_merge([$STUDENT_ID], $grade_tids)
);
$grades_ok = true;
foreach ($grade_certs_after as $cert) {
    $tid = (int) $cert['training_id'];
    $pair = $GRADES[$tid] ?? null;
    $match = $pair !== null
        && (string) $cert['grade'] === (string) $pair['grade']
        && (string) $cert['grade_label'] === (string) $pair['grade_label'];
    if (!$match) {
        $grades_ok = false;
        echo "FAIL - certificate for training {$tid}: expected " . ($pair['grade'] ?? '?') . " / " . ($pair['grade_label'] ?? '?') . ", got " . var_export($cert['grade'], true) . " / " . var_export($cert['grade_label'], true) . "\n";
    }
}
seed_check('all issued/revoked dataset certificates carry the expected grade data', $grades_ok);
seed_check("$grades_assigned new grade(s) assigned (0 on idempotent re-run)", $grades_assigned >= 0);

/*
 |--------------------------------------------------------------------------
 | Unfinished training proof (Case A: ends_at > NOW => NOT eligible/requestable)
 |--------------------------------------------------------------------------
 */

echo "\n== Timing gate: unfinished training stays unavailable ==\n";

$unfinished_row = db_fetch_one(
    "SELECT ends_at, ends_at > NOW() AS running_now FROM training_listings WHERE id = ? LIMIT 1",
    [$UNFINISHED]
);
$unfinished_end = (string) ($unfinished_row['ends_at'] ?? '');
seed_check("unfinished training $UNFINISHED exists with ends_at in the future", (int) ($unfinished_row['running_now'] ?? 0) === 1);

$eligible_unfinished = certificate_repository_eligible(['student_id' => $STUDENT_ID, 'training_id' => $UNFINISHED]);
seed_check("$UNFINISHED is NOT in the eligible feed (ends_at > NOW(), Case A)", count($eligible_unfinished) === 0);

$req_unfinished = certificate_service_request($student_user, ['training_id' => $UNFINISHED]);
seed_check('requesting certificate for the still-running training is rejected (422)', ($req_unfinished['success'] ?? true) === false);

/*
 |--------------------------------------------------------------------------
 | Final state verification
 |--------------------------------------------------------------------------
 */

echo "\n== Final dataset verification ==\n";

$all_certs = db_fetch_all(
    "SELECT c.id, c.training_id, c.status, c.certificate_code, c.requested_at,
            c.approved_at, c.revoked_at, c.revocation_reason, t.is_paid, t.ends_at
     FROM certificates c
     JOIN training_listings t ON t.id = c.training_id
     WHERE c.student_id = ?
     ORDER BY c.training_id",
    [$STUDENT_ID]
);

$by_status = ['pending' => 0, 'issued' => 0, 'revoked' => 0];
$all_finished_ok = true;
foreach ($all_certs as $c) {
    $st = strtolower((string) $c['status']);
    if (isset($by_status[$st])) {
        $by_status[$st]++;
    }
    if ($st !== 'pending') {
        if (($c['certificate_code'] ?? '') === '' || ($c['approved_at'] ?? '') === '') {
            $all_finished_ok = false;
        }
    }
    if ($st === 'revoked') {
        if (($c['revoked_at'] ?? '') === '' || trim((string) ($c['revocation_reason'] ?? '')) === '') {
            $all_finished_ok = false;
        }
    }
}
$total_certs = count($all_certs);

seed_check('certificate counts: pending=5, issued=6, revoked=3', $by_status['pending'] === 5 && $by_status['issued'] === 6 && $by_status['revoked'] === 3);
seed_check('total certificates for student = 14', $total_certs === 14);
seed_check('every issued/revoked cert carries a generated number + issued_at; revoked keep reasons', $all_finished_ok);

/*
| Grade rules that must hold after the seeder:
|   issued   -> grade + grade_label are populated
|   revoked  -> preserves the historical grade (issued before revocation)
|   pending  -> grade + grade_label stay NULL
|   eligible / unfinished -> no certificate row, hence no grade at all
| Distribution is not uniform (at least 3 distinct grades on issued certs).
*/
$grade_rows = db_fetch_all(
    "SELECT c.status, c.grade, c.grade_label
     FROM certificates c
     WHERE c.student_id = ?
     ORDER BY c.training_id",
    [$STUDENT_ID]
);
$issued_without_grade = 0;
$revoked_without_grade = 0;
$pending_with_grade = 0;
$issued_grades = [];
foreach ($grade_rows as $gr) {
    $st = strtolower((string) $gr['status']);
    $has = $gr['grade'] !== null && (string) $gr['grade'] !== '' && $gr['grade_label'] !== null && (string) $gr['grade_label'] !== '';
    if ($st === 'issued') {
        if (!$has) { $issued_without_grade++; }
        $issued_grades[] = (string) $gr['grade'];
    }
    if ($st === 'revoked' && !$has) { $revoked_without_grade++; }
    if ($st === 'pending' && $has) { $pending_with_grade++; }
}
sort($issued_grades);
seed_check('every issued certificate has grade + grade_label', $issued_without_grade === 0);
seed_check('every revoked certificate preserves its historical grade', $revoked_without_grade === 0);
seed_check('no pending certificate carries a grade (all NULL)', $pending_with_grade === 0);
seed_check('issued certificates use a non-uniform grade distribution', count(array_unique($issued_grades)) >= 3);

$eligible_now = certificate_repository_eligible(['student_id' => $STUDENT_ID]);
$eligible_ids = array_map(static fn ($i) => (int) $i['training_id'], $eligible_now);
$expected = array_map('intval', $ELIGIBLE_IDS);
sort($eligible_ids);
sort($expected);
seed_check('eligible set equals exactly the 8 finished, undocumented trainings', $eligible_ids === $expected);
seed_check('every eligible training has ends_at <= NOW()', (int) ((db_fetch_one(
    "SELECT COUNT(*) AS n FROM training_listings
     WHERE id IN (" . implode(',', array_fill(0, count($ELIGIBLE_IDS), '?')) . ")
       AND ends_at <= NOW()",
    $ELIGIBLE_IDS
))['n'] ?? 0) === count($ELIGIBLE_IDS));

$dataset_spec_mismatch = db_fetch_all(
    "SELECT t.id
     FROM training_listings t
     JOIN students s ON s.id = ?
     WHERE t.id BETWEEN 100400 AND 100422
       AND t.specialization_id <> s.specialization_id",
    [$STUDENT_ID]
);
seed_check('every dataset training (100400-100422) matches the student specialization (199)', count($dataset_spec_mismatch) === 0);

$paid_certs = 0;
$paid_code_rows = db_fetch_all(
    "SELECT c.id, c.status, t.is_paid FROM certificates c
     JOIN training_listings t ON t.id = c.training_id WHERE c.student_id = ?",
    [$STUDENT_ID]
);
foreach ($paid_code_rows as $c) {
    if ((int) $c['is_paid'] === 1) {
        $paid_certs++;
    }
}
seed_check('paid/free certificate variety (7 paid / 7 free across the dataset)', $paid_certs === 7);

/*
 |--------------------------------------------------------------------------
 | MASAR collection variables
 |--------------------------------------------------------------------------
 */

$pending_cert       = dataset_cert($STUDENT_ID, 100408);
$pending_plus       = db_fetch_all("SELECT COUNT(*) AS n FROM certificates WHERE student_id = ? AND status = 'pending'", [$STUDENT_ID]);
$issued_cert        = dataset_cert($STUDENT_ID, 100413);
$issued_paid_cert   = dataset_cert($STUDENT_ID, 100416);
$revoked_cert       = dataset_cert($STUDENT_ID, 100419);

echo "\n== Collection variables to set in MASAR.json ==\n";
echo "  certificate_training_id          = " . $ELIGIBLE_IDS[0] . "   (free, eligible - Request target)\n";
echo "  certificate_training_id_paid     = " . $ELIGIBLE_IDS[4] . "   (paid, eligible)\n";
echo "  certificate_pending_id           = " . (int) ($pending_cert['id'] ?? 0) . "   (stable pending)\n";
echo "  certificate_id                   = " . (int) ($pending_cert['id'] ?? 0) . "   (Get Certificate By ID / Verify)\n";
echo "  certificate_issued_id            = " . (int) ($issued_cert['id'] ?? 0) . "   (stable issued, free)\n";
echo "  certificate_issued_id_paid       = " . (int) ($issued_paid_cert['id'] ?? 0) . "   (stable issued, paid)\n";
echo "  certificate_revoked_id           = " . (int) ($revoked_cert['id'] ?? 0) . "   (stable revoked)\n";
echo "  certificate_unfinished_id        = " . $UNFINISHED . "   (running training, NOT eligible)\n";
echo "  certificate_issued_code          = " . (string) ($issued_cert['certificate_code'] ?? '') . "   (Verify Certificate code)\n";
echo "  certificate_revoked_code         = " . (string) ($revoked_cert['certificate_code'] ?? '') . "\n";
echo "  certificate_eligible_student     = " . $STUDENT_ID . "\n";
echo "  certificate_company_id           = " . $COMPANY_ID . "\n";
echo "  certificate_company_user_id      = " . $COMPANY_UID . "\n";
echo "  certificate_admin_user_id        = " . $admin_user_id . "\n";
echo "  certificate_revoke_reason        = Administrative verification failed\n";

echo "\n== Per-state training ids ==\n";
echo '  eligible  : ' . implode(', ', $ELIGIBLE_IDS) . "\n";
echo '  pending   : ' . implode(', ', $PENDING_IDS) . "\n";
echo '  issued    : ' . implode(', ', $ISSUED_IDS) . "\n";
echo '  revoked   : ' . implode(', ', $REVOKED_IDS) . "\n";
echo '  unfinished: ' . $UNFINISHED . " (ends_at {$unfinished_end}, running)\n";

echo "\n=== " . ($failures === 0 ? 'ALL PASS' : ($failures . " FAILURE(S)")) . " ===\n";
exit($failures === 0 ? 0 : 1);